select
    s.*,
    e.play_id,
    e.savant_pitch_source,
    e.cap_index,
    e.half_inning,
    e.catcher,
    e.catcher_name,
    e.team_batting,
    e.team_fielding,
    e.team_batting_id,
    e.team_fielding_id,
    e.result,
    e.result_code,
    e.pre_balls,
    e.pre_strikes,
    e.call,
    e.call_name,
    e.pitch_call,
    e.is_strike_swinging,
    e.balls_and_strikes,
    e.start_speed,
    e.end_speed,
    e.sz_depth,
    e.sz_width,
    e.plate_time,
    e.spin_rate as savant_spin_rate,
    e.break_x,
    e.break_z,
    e.px,
    e.pz,
    e.pfx_z_with_gravity,
    e.break_x_inches,
    e.break_z_induced_inches,
    e.break_z_with_gravity_inches,
    e.savant_is_in_zone,
    e.is_in_zone,
    e.is_sword,
    e.is_bip_out,
    e.is_abs_challenge,
    e.abs_challenge_is_batter,
    e.abs_challenge_is_in_progress,
    e.abs_challenge_is_overturned,
    e.abs_challenge_challenge_team_id,
    round((e.abs_challenge_edge_distance * 12)::numeric, 2) as abs_challenge_edge_distance,
    e.abs_challenge_challenging_player_id,
    e.abs_challenge_challenging_player_type,
    (e.play_id is not null) as has_statcast_extra
from {{ source('warehouse', 'statcast') }} as s
left join {{ source('warehouse', 'statcast_extra') }} as e
    on s.game_pk = e.game_pk
    and s.at_bat_number = e.ab_number
    and s.pitch_number = e.pitch_number
